import type { Metadata } from "next";
import { Poppins, } from "next/font/google";
import "./globals.css";
import HomeLayout from "./HomeLayout";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Online Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <HomeLayout>
          {children}
        </HomeLayout>
      </body>
    </html>
  );
}
